"Computer Architecture":
  - '**/computer_architecture/**'
Maths:
  - '**/computational_mathematics/**'
  - '**/maths/**'
Microelectronics:
  - '**/microelectronics/**'
Java:
  - '**/oop/**'
"Repository Changes":
  - '*'
  - '.github/**'
