"Computer Architecture":
  - changed-files:
    - any-glob-to-any-file: "**/computer_architecture/**"
Maths:
  - changed-files:
    - any-glob-to-any-file: ["**/computational_mathematics/**", "**/maths/**"]
Microelectronics:
  - changed-files:
    - any-glob-to-any-file: "**/microelectronics/**"
Java:
  - changed-files:
    - any-glob-to-any-file: "**/oop/**"
"Repository Changes":
  - changed-files:
    - any-glob-to-any-file: ["*", ".github/**"]
