BUILD_DIR := build
all:
	clang -fopenmp -std=c23 -Wall -Werror -o ${BUILD_DIR}/2_point 2_point.c
	clang -fopenmp -std=c23 -Wall -Werror -o ${BUILD_DIR}/3_1_point 3_1_point.c
	clang -fopenmp -std=c23 -Wall -Werror -o ${BUILD_DIR}/3_2_point 3_2_point.c
	clang -fopenmp -std=c23 -Wall -Werror -o ${BUILD_DIR}/4_point 4_point.c
